name:  Send Email # Nombre del actions

on: # Evento que dispara el actions
    pull_request:
        branches: [ main ] # Rama que dispara el actions
    push: # Evento push que dispara el actions
        branches: [ main ] # Rama que dispara el actions 

concurrency: # Evita que se ejecuten múltiples acciones al mismo tiempo
    group: ${{ github.workflow }}-${{ github.ref }} # Grupo de concurrencia basado en el nombre del workflow y la referencia de la rama
    cancel-in-progress: true # Cancela las ejecuciones en progreso si se inicia una nueva

jobs: # Jobs que se ejecutan en el actions
    tests: # Job principal
        name: Django Pytest # Nombre del job
        runs-on: ubuntu-latest # Sistema operativo donde se ejecuta el job
        time-out-minutes: 3
        env:
            PYTHONPATH: ${{ github.workspace }} /itec2025
            PYTHONDONTWRITEBYTECODE: 1
            PYTHONUNBUFFERED: 1

        steps: # Pasos que se ejecutan en el job
            - name: Checkout code # Nombre del paso
              uses: actions/checkout@v3 # Acción para hacer checkout del código

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                python-version: "3.12" # Versión de Python a usar
                cache: "pip" # Cache para pip

            - name: Install dependencies # Nombre del paso
              run: | # Comandos a ejecutar
                    python -m pip install --upgrade pip
                    pip install requirements.txt 
            - name: Run tests # Nombre del paso
              run: | 
                    pytest -m python -q
        notify:
            name: Notify on success
            needs: tests
            if: success()
            runs-on: ubuntu-latest
            steps:
              - name: Send email
                uses: dawidd6/action-send-mail@v3
                with:
                  server_address: ${{ secrets.EMAIL_HOST }}
                  server_port: ${{ secrets.EMAIL_PORT }}
                  username: ${{ secrets.EMAIL_USER }}
                  password: ${{ secrets.EMAIL_PASSWORD }}
                  subject: Tests Passed Successfully
                  to: ${{ secrets.EMAIL_TO }}
                  from: ${{ secrets.EMAIL_FROM }}
                  secure:
                  body: |
                    <h3>All tests have passed successfully!</h3>
                    <p>The latest commit has passed all tests.</p>
                    <p> Autor del pr ${{ github.event.pull_request.user.login }} </p>
                  

